### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by chuanshan-ali** [quininer/ktls#3]
Using the ubuntu 18.04, `sudo modprobe tls` and `cargo test`

```
test test_tls12 ... FAILED

failures:

---- test_tls12 stdout ----
thread 'test_tls12' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 92, kind: Other, message: "Protocol not available" }', src/libcore/result.rs:999:5
```

**Comment by quininer** [comment]
It's working for me. can you print `modinfo tls`?

![Screenshot_20190822_103851](https://user-images.githubusercontent.com/6286761/63481738-0a318980-c4c9-11e9-8cdf-a469f964b166.png)

Anyway, I don't have much energy to play this project. I think using `zero-copy tcp` + `io uring` + `userspace tls` is a better direction.

**Comment by chuanshan-ali** [comment]
![image](https://user-images.githubusercontent.com/54096794/63482147-69dc6480-c4ca-11e9-9eba-9223206d8a7e.png)

Agree, and playing KTLS just for a research.

**Comment by quininer** [comment]
It has no signature, is this your own compiled kernel module? I am using the Linux 5.2.8 kernel for ArchLinux and it works fine.

**Comment by chuanshan-ali** [comment]
No, the kernel is provided in ubuntu 18.04. I tried on Manjaro with 4.19 and pass all tests. I don't know what is the problem with ubuntu...

**Comment by quininer** [comment]
This may be because linux 4.15 does not support [TLS RX](https://lwn.net/Articles/748883/). It is provided in linux 4.17.

**Comment by chuanshan-ali** [comment]
Yeah, `sudo apt install linux-image-5.0.0-*` also solve the problem. Thanks
